var balls = [
    "I do things, just not very well",
    "based + Tailwindpilled",
    "404: brain not found",
    "#kb43ver RIP the legend",
    "Go donate to 43i.org",
    "Red Bull is overrated",
    "My dog has 1 braincell (that's still more than me)",
    "kys (keep yourself safe)",
    "You just lost the game!",
    "A Who? A What? A LERODGE!",
    "You're telling me a SHRIMP fried this rice????",
    "Top 10 best waterslides",
    "Moco de Gorila goes hard",
    "BRING ME A SHRUBBERY!",
    "What is the airspeed velocity of an unladen swallow?",
    "Life.... is Roblox",
    "Tell 'em to bring out the whole ocean!",
    "Back to the lab again, yo",
    "*extremely loud incorrect buzzer*",
    "hilarious entities",
    "DIS MY BROTHER BILO BTW",
    "dems real apples",
    "Charlie DiNapoli! 🍷",
    "Harrison did nothing",
    "did anthony every wash those pants (no)",
    "this site was built using assembly.",
    "this site was built using brainfuck.",
    "this site was built using cheap child labor.",
    "pizza my heart parking lot",
    "gorge washingmachine is my fav president",
    "exhaust pipes better run from kade",
    "fortinayti ora baba gee?",
    "sam sulek pls sit on me",
    "RIP JStark",
    "Your majesty, the second Big Ben has been hit",
    "oi mate, you fancy drinkin a bo oh oh wo oh on a chewsday innit?",
    "domestic terrorizzt 🥶🥶",
    "drippy grandma",
    "jesse james fan club official",
    "rizzyjames never dies",
    "os.remove('C://Windows/System32')",
    "sudo rm -rf",
    "waltuh...",
    "if you have a better fish pun, please let minnow",
    "i am going to cry and then i will stop but then i will do some more later",
    "chatgpt my beloved <3",
    "its tea time innit",
    "https://cornhub.website",
    "shadow wizard money gang",
    "Call me axparagus!",
    "our stand at Yser will be the end of the race to the sea",
    "if charlie wants to tangle, now he'll have 2 to dodge",
    "twice they attack, twice they're beaten back",
    "'You'd better fucking learn swedish' - Joakim Broden",
    "United they're strong, united they're holding the line",
    "no surrender, fight until the end!",
    "javascriptmaxxing"
  ];