const contentData = [
    {
      "align": "c",
      "title": "<h1 style='font-size: 50px'>Sizes and Scales of the Universe</h1>",
      "innerHTML": "Graeme Kieran"
    },
    {
      "align": "l",
      "title": "Where are we in the grand scheme of things?",
      "innerHTML": "The little blue marble that we call home is situated within a solar system in the Milky Way Galaxy, which you've probably heard of at least once. Do you know how many stars are in the entire Milky Way? <strong> Hundreds of billions </strong>. That's a crazy huge number, and do bear in mind that not every one of these stars is exactly like our Sun; some are bigger, some are smaller. If you thought this number was big, you're in for a treat because it's gonna get a lot bigger. <br /><br /> I'd rather your head stay intact and not explode all over wherever you are, so I'll use a scale you'll be all too familiar with: the average classroom, a place I'm sure you've spent countless hours. Let's say we shrunk the Earth down to be the size of a classroom. How big do you think a city like San Francisco might be? Turns out it's about the size of a single penny now. You don't just want to learn about Earth now, do you? Okay, fine. If we took the entire Solar System and put it in a classroom, you would see......not much actually, save for an extremely bright grain of sand in the center which is, of course, our Sun. <br /><br /> Ours isn't the only solar system though. Remember the hundreds of billions of stars in the Milky Way? If we were to fit all of them into the classroom, each one would be the size of a single atom. Despite their miniscule size, the room would be filled with light because every single star you be emitting a ton of light, as stars usually do. <br /><br />Galaxies just like ours are also clustered together in groups known as galactic groups. The one we're in is called the Local Group, and contains around a dozen or so other galaxies. When galactic groups cluster together, thats known as a cluster, and when clusters cluster, it makes a supercluster. The known Universe is filled with hundreds and thousands of these superclusters with potentially into the trillions of galaxies. If all of these were to somehow be in a single classroom, it would appear as if the room was filled with brightly glowing cobwebs, floor-to-ceiling, wall-to-wall. Pretty crazy to think about, right?"
    },
    {
      "align": "r",
      "title": "What and how much is out there?",
      "innerHTML":"As I mentioned before, there are billions if not trillions of other stars in the universe, each with their own systems. Some stars have fewer planets than ours, and some stars have more planets than ours. However, we on Earth are in a very lucky position. In order for a planet to be habitable, it needs to be within a certain \"Goldilocks zone\" in its distance from the central star. This is because, as you can imagine, being too close to a large floating ball of nuclear fusion is not really that comfortable. Conversely, stars provide their planets with warmth that is needed for life, thus faraway planets are freezing cold and can only support very primitive life, if any at all.<br /><br />To give you an idea of how many stars there are in the Universe, think of the last time you went to the beach and looked at the sand. Remember how small each grain is? How many do you think there are in not just your hand, not just the beach, but on earth in general? A pretty good estimate suggests that there are  around 10^19 grains of sand. Now comparing this number to a mathematical estimate of how many stars exist (10^23), we can see that there are tens of thousands of stars for EVERY SINGLE grain of sand on Earth. That's an absolutely mind-boggling number that is almost impossible to wrap around your head."
    },
    {
      "align": "l",
      "title": "Are we alone?",
      "innerHTML":"This is a question that is often asked by curious minds like yours and researchers alike. Italian-American physicist Enrico Fermi asked a very similar question - dubbed the Fermi Paradox - Where are they? As in, if there indeed are intelligent life forms in the universe, why haven't we seen or heard from them? For years, scientists, philosophers, and the like have been trying to answer this question, and have come up with several possibilities and theories. Here's a rough breakdown of what they're thinking: <br /><ul><li><strong>The Universe is huge.</strong>Because of the vast size of the Universe and just how many galaxies, solar systems, and planets there are, there definitely could be life somewhere. </li><li><strong>Life could be common.</strong> Given the vast amount of planets, many believe that life could be incredibly common in the Universe.</li><li><strong>Where is everyone?</strong> If life is so common, why have we only seen ours? There are quite a few theories and opinions on this, but here are the prevalent ones:</li><ul><li><strong>Rare conditions.</strong>The conditions to support the development of life (like we have here on Earth) could be incredibly rare.</li><li><strong>Self-Destruction.</strong> Developed, intelligent civilizations might destroy themselves before being able to carry out interstellar travel or communication.</li><li><strong>Distance and time.</strong> As I'll get into in a moment, the distances in the universe and subsequently the time taken for even light to travel these distances are so large that we are out of range of any emitted signals.</li><li><strong>We aren't listening right.</strong> Other civilizations are sending out signals, but we do not have the technology required to receive them.</li></ul></ul>"
    },
    {
      "align": "r",
      "title": "How do distance and time on earth compare to distance and time on a cosmic scale?",
      "innerHTML": "On a cosmic scale, distances and times are much larger that we're used to here on Earth. Distances that seem large on Earth, like a mile or kilometer, are insignificant on the scale of the Universe. These units that we consider big are so small on a cosmic scale that we have created larger units to use in astronomy. The two most common are AU or Astronomical Unit, which is the average distance from the Earth to our Sun, and the Light Year, which is the distance traveled by light in 1 year. To illustrate the immense distances as they compare to scales we know, let's assume an average house is our starting point, and scale up. A small to medium city is on the order of a thousand times the size, the planet on the order of a million times larger, the solar system a billion times larger, all the way up to galaxies which are a quintillion or sextillion times larger, and finally the observable universe sitting at a cool septillions of times larger than your house.  <br /><br/>Light is the fastest thing in the Universe, but on a cosmic scale, it its incredibly slow. Remember earlier when I said that our galaxy had hundreds of billions of stars, and if it was scaled to fit in a classroom all you would see is light? On that same distance scale, light would take a hundred years to travel a single centimeter.  Light, the fastest thing in the universe, taking a hundred years to travel a single scaled centimeter.  <br/><br/>The closest galaxy to us is Alpha Centauri, but even though cosmically it is close, a beam of light traveling from here to there would take four whole years to arrive. This sounds like it could only be a problem, but the delay in fact has both benefits and drawbacks. One of the greatest and most influential benefits of this is that it has allowed us to essentially see back in time. Using Alpha Centauri as an example, when we point a telescope there, we aren't seeing it as it exists in the moment, but rather as it existed 4 years prior because the light emitted that we are seeing took 4 years to actually reach our telescope and then our eyes. Do keep in mind too,  that this is the closest galaxy, and there are many others hundreds and thousands of times farther away. Because of this interesting quirk, we've been able to discover a lot about the formation of the Universe, stars, and planets because we can look at far away examples and essentially see back in time to what young stars and planets look like. It is due to these observations that we know how our galaxy and Solar System came to be."
    },
    {
      "align": "l",
      "title": "Can I dump you for an intergalactic Significant Other?",
      "innerHTML": "No matter how hard you try, or whatever VPN you install, you'll never see an advertisement for \"HOT SINGLES IN YOUR GALACTIC SUPERCLUSTER!!!!\" <br/><br />Why though? This is one of those drawbacks of light traveling so 'slowly' that I mentioned earlier. Unfortunately, due to the sheer amount of time it takes for light to travel between galaxies, communication and by extension dating are made extremely inefficient and difficult. Lets imagine that (even though it is widely considered to be disproven) there is a planet with advanced life somewhere in Alpha Centauri, and lets assume that this planet is a carbon copy of Earth. If you were to try to text someone on the other planet, your message would take 4 years to get there, then they would ghost you for like a year, then their message would take 4 years to get back. Again, this is the closest galaxy. This also means that if you wanted to search for someone who is your age, assuming you're 17 you would have to look for a 13 year old, then by the time you message them and they message back, you're both 22 and forgot about eachothers existence. So in short, no you absolutely cant dump me for the interstellar dating scene."
    },
    {
      "align": "r",
      "title": "Personal reflection",
      "innerHTML": "When I put Astrophysics in my course request last year, I wasn't sure what I was getting myself into. After this first unit, I feel like I have learned a lot of genuinely interesting facts about our world and Universe. My perspective of our place in the Universe before this class was that we are really small in comparison, though I didn't know how much smaller we truly were. This class has put into perspective everything in the Universe, from the smallest atom to the entire known Universe, in scales that I understand and have a natural understanding of. I especially enjoyed the part of the lecture where we were compared to smaller things like atoms and subatomic particles, as it made a very interesting comparison to the Universe that I had never considered before"
    },
    {
      "align": "l",
      "title": "The End. Thanks for watching and I hope you learned something!",
      "innerHTML": "Made with ❤️ by Graeme Kieran <br /><br />Powered by Three.js <br /><br />Hosted by Github <br /><br /> <a style='color: white'href='https://github.com/bean-frog/size-and-scale'>Source code</a>"
    }
  ];
  